leveldb:
  bloom_bits: 10
  enable_direct_io: false
  enable_compaction: true
  thread_compaction: 8
  block_cache_size: "128MB" # e.g. "100MB" or "10GB"
  memtable_size: "128MB" # e.g. "64MB"
  sst_file_size: "32MB"
  db_size: "32GB"
pmrocksdb:
  bloom_bits: 10
  enable_direct_io: false
  enable_compaction: true
  thread_compaction: 8
  block_cache_size: "128MB" # e.g. "100MB" or "10GB"
  memtable_size: "128MB" # e.g. "64MB"
  sst_file_size: "32MB"
  db_size: "32GB"
pmemkv:
  create_if_missing: true
  db_size: "32GB"
  engine_type: "radix"
fastfair:
  db_size: "64GB"
listdb:
  pool_size: "64MB"
utree:
  db_size: "64GB"
neopmkv:
  db_size: "64GB"
  chunk_size: "128MB"
  enable_pbrb: true
  async_pbrb: true
  max_page_num: 6621440
