leveldb:
  bloom_bits: 10
  enable_direct_io: false
  enable_compaction: true
  thread_compaction: 8
  block_cache_size: "128MB" # e.g. "100MB" or "10GB"
  memtable_size: "128MB" # e.g. "64MB"
  sst_file_size: "32MB"
  db_size: "16GB"
pmrocksdb:
  bloom_bits: 10
  enable_direct_io: false
  enable_compaction: true
  thread_compaction: 8
  block_cache_size: "128MB" # e.g. "100MB" or "10GB"
  memtable_size: "128MB" # e.g. "64MB"
  sst_file_size: "32MB"
  db_size: "16GB"
pmemkv:
  create_if_missing: true
  db_size: "16GB"
  engine_type: "radix"
fastfair:
  db_size: "16GB"
listdb:
  pool_size: "64MB"
utree:
  db_size: "16GB"
neopmkv:
  db_size: "16GB"
  chunk_size: "64MB"
